// Converts verified research JSON (collected from Crossref, ISBN catalogues,
// ClinicalTrials.gov and Wikimedia Commons) into typed data modules in src/data.
// Usage: node scripts/import-library.mjs <dir-with-json>
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const dir = process.argv[2];
if (!dir) throw new Error('Pass the directory containing the research JSON files.');
const out = new URL('../src/data/', import.meta.url);
const read = f => (existsSync(join(dir, f)) ? JSON.parse(readFileSync(join(dir, f), 'utf8')) : {});

const header = '// Generated by scripts/import-library.mjs from verified source records. Edit the source JSON, not this file.\n';
const emit = (file, typeImport, name, type, records) =>
  writeFileSync(
    new URL(file, out),
    `${header}import type { ${type} } from '${typeImport}';\n\nexport const ${name}: ${type}[] = ${JSON.stringify(records, null, 2)};\n`,
  );

const uniqueBySlug = records => {
  const seen = new Set();
  return records.filter(r => (seen.has(r.slug) ? false : (seen.add(r.slug), true)));
};

const divisionFiles = ['divisions-a.json', 'divisions-b.json', 'divisions-c.json'].map(read);
// Identifiers are strings even when a source returns them as numbers.
const asStrings = (record, keys) => {
  for (const key of keys) if (record[key] !== undefined && record[key] !== null) record[key] = String(record[key]);
  return record;
};
const publications = uniqueBySlug(divisionFiles.flatMap(f => f.publications ?? [])).map(p => asStrings(p, ['pmid', 'pmcid', 'volume', 'issue', 'pages']));
// The same edition can arrive from two division lists; merge on ISBN and keep every division.
const byIsbn = new Map();
for (const book of divisionFiles.flatMap(f => f.books ?? []).map(b => ({ authors: [], editors: [], ...b }))) {
  const key = book.isbn13 ?? book.slug;
  const seen = byIsbn.get(key);
  if (seen) seen.divisions = [...new Set([...seen.divisions, ...book.divisions])];
  else byIsbn.set(key, book);
}
const books = uniqueBySlug([...byIsbn.values()]);
const studies = uniqueBySlug(read('studies.json').studies ?? []).map(s => ({ ...s, resultsPublications: s.resultsPublications?.map(r => asStrings(r, ['pmid'])) }));
const media = read('media-education.json');

if (publications.length) emit('publications.ts', '@/lib/publications', 'publicationRecords', 'Publication', publications);
if (books.length) emit('books.ts', '@/lib/books', 'bookRecords', 'Book', books);
if (studies.length) emit('studies.ts', '@/lib/research', 'studyRecords', 'StudyRecord', studies);
if (media.illustrations || media.resources) {
  writeFileSync(
    new URL('media.ts', out),
    `${header}import type { Illustration } from '@/lib/illustrations';\nimport type { LearningResource } from '@/lib/education';\n\n` +
      `export const illustrationRecords: Illustration[] = ${JSON.stringify(uniqueBySlug(media.illustrations ?? []), null, 2)};\n\n` +
      `export const resourceRecords: LearningResource[] = ${JSON.stringify(uniqueBySlug(media.resources ?? []), null, 2)};\n`,
  );
}
console.log({ publications: publications.length, books: books.length, studies: studies.length, illustrations: media.illustrations?.length ?? 0, resources: media.resources?.length ?? 0 });
