// Generated by scripts/import-library.mjs from verified source records. Edit the source JSON, not this file.
import type { Book } from '@/lib/books';

export const bookRecords: Book[] = [
  {
    "authors": [
      {
        "name": "Timothy L. Lash"
      },
      {
        "name": "Tyler J. VanderWeele"
      },
      {
        "name": "Sebastien Haneuse"
      },
      {
        "name": "Kenneth J. Rothman"
      }
    ],
    "editors": [],
    "slug": "modern-epidemiology-4th-edition",
    "title": "Modern Epidemiology",
    "edition": "4th edition",
    "category": "textbook",
    "publisher": "Wolters Kluwer / Lippincott Williams & Wilkins",
    "year": 2021,
    "isbn13": "9781451193282",
    "pages": 1250,
    "url": "https://shop.lww.com/Modern-Epidemiology/p/9781451193282",
    "summary": "A standard graduate-level reference on the principles and methods of epidemiologic research, from study design, bias and precision through to causal diagrams, regression and bias analysis. The fourth edition adds material on newer approaches such as mediation analysis and quasi-experimental designs.",
    "keywords": [
      "epidemiology",
      "study design",
      "causal inference",
      "bias analysis",
      "biostatistics"
    ],
    "divisions": [
      "research"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Warren S. Browner"
      },
      {
        "name": "Thomas B. Newman"
      },
      {
        "name": "Steven R. Cummings"
      },
      {
        "name": "Deborah G. Grady"
      },
      {
        "name": "Alison J. Huang"
      },
      {
        "name": "Alka M. Kanaya"
      },
      {
        "name": "Mark J. Pletcher"
      }
    ],
    "editors": [],
    "slug": "designing-clinical-research-5th-edition",
    "title": "Designing Clinical Research",
    "edition": "5th edition",
    "category": "handbook",
    "publisher": "Wolters Kluwer / Lippincott Williams & Wilkins",
    "year": 2022,
    "isbn13": "9781975174408",
    "pages": 468,
    "url": "https://shop.lww.com/Designing-Clinical-Research/p/9781975174408",
    "summary": "A practical guide to planning clinical and public-health studies, covering how to frame a research question, choose a design, estimate sample size and run trials and observational studies. The fifth edition adds chapters on qualitative and community-engaged research and expanded discussion of confounding and directed acyclic graphs.",
    "keywords": [
      "clinical research",
      "study design",
      "sample size",
      "clinical trials",
      "research protocol"
    ],
    "divisions": [
      "research",
      "clinical-medicine"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "Joseph Loscalzo"
      },
      {
        "name": "Anthony S. Fauci"
      },
      {
        "name": "Dennis L. Kasper"
      },
      {
        "name": "Stephen L. Hauser"
      },
      {
        "name": "Dan L. Longo"
      },
      {
        "name": "J. Larry Jameson"
      }
    ],
    "slug": "harrisons-principles-of-internal-medicine-21st-edition",
    "title": "Harrison's Principles of Internal Medicine",
    "edition": "21st edition",
    "category": "reference",
    "publisher": "McGraw Hill",
    "year": 2022,
    "isbn13": "9781264268504",
    "url": "https://ci.nii.ac.jp/ncid/BC10797213",
    "summary": "A two-volume reference covering the pathophysiology, diagnosis and management of diseases across internal medicine. Long regarded as a core text for physicians and medical trainees, the 21st edition adds chapters on topics such as precision medicine and machine learning in clinical care.",
    "keywords": [
      "internal medicine",
      "clinical medicine",
      "pathophysiology",
      "diagnosis",
      "therapeutics"
    ],
    "divisions": [
      "clinical-medicine"
    ],
    "verifiedVia": "Open Library"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "Adam Feather"
      },
      {
        "name": "David Randall"
      },
      {
        "name": "Mona Waterhouse"
      }
    ],
    "slug": "kumar-and-clarks-clinical-medicine-10th-edition",
    "title": "Kumar and Clark's Clinical Medicine",
    "edition": "10th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2020,
    "isbn13": "9780702078682",
    "url": "https://shop.elsevier.com/books/kumar-and-clarks-clinical-medicine/feather/978-0-7020-7868-2",
    "summary": "A widely used clinical medicine textbook for medical students and junior doctors, organised by body system and clinical specialty. The tenth edition, produced by a new editorial team, adds chapters on clinical method, frailty and multimorbidity, public health and sepsis.",
    "keywords": [
      "clinical medicine",
      "medical education",
      "internal medicine",
      "clinical skills"
    ],
    "divisions": [
      "clinical-medicine"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Michael G. Newman"
      },
      {
        "name": "Henry Takei"
      },
      {
        "name": "Perry R. Klokkevold"
      },
      {
        "name": "Fermin A. Carranza"
      }
    ],
    "editors": [],
    "slug": "newman-carranzas-clinical-periodontology-13th-edition",
    "title": "Newman and Carranza's Clinical Periodontology",
    "edition": "13th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2018,
    "isbn13": "9780323523004",
    "url": "https://shop.elsevier.com/books/newman-and-carranzas-clinical-periodontology/newman/978-0-323-52300-4",
    "summary": "A long-standing periodontology textbook spanning the basic science of periodontal tissues, disease pathogenesis and diagnosis, and treatment from non-surgical therapy to reconstructive and implant procedures. It is used by dental students, periodontal residents and practising clinicians.",
    "keywords": [
      "periodontology",
      "periodontal disease",
      "dental implants",
      "periodontal therapy"
    ],
    "divisions": [
      "dentistry-oral-sciences"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "Tord Berglundh"
      },
      {
        "name": "William V. Giannobile"
      },
      {
        "name": "Niklaus P. Lang"
      },
      {
        "name": "Mariano Sanz"
      }
    ],
    "slug": "lindhes-clinical-periodontology-and-implant-dentistry-7th-edition",
    "title": "Lindhe's Clinical Periodontology and Implant Dentistry",
    "edition": "7th edition",
    "category": "reference",
    "publisher": "Wiley-Blackwell",
    "year": 2021,
    "isbn13": "9781119438885",
    "pages": 1360,
    "url": "https://www.wiley.com/en-us/Lindhe%27s+Clinical+Periodontology+and+Implant+Dentistry%2C+7th+Edition-p-9781119438885",
    "summary": "A two-volume reference work on periodontology and implant dentistry, covering basic biology, disease mechanisms, examination and the full range of periodontal and implant therapy. The seventh edition reflects the 2017 classification of periodontal and peri-implant diseases.",
    "keywords": [
      "periodontology",
      "implant dentistry",
      "peri-implant disease",
      "oral biology"
    ],
    "divisions": [
      "dentistry-oral-sciences"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Patricia A. Potter"
      },
      {
        "name": "Anne G. Perry"
      },
      {
        "name": "Patricia A. Stockert"
      },
      {
        "name": "Amy Hall"
      },
      {
        "name": "Wendy R. Ostendorf"
      }
    ],
    "editors": [],
    "slug": "potter-perry-fundamentals-of-nursing-12e",
    "title": "Fundamentals of Nursing",
    "edition": "12th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2025,
    "isbn13": "9780443124068",
    "pages": 1536,
    "url": "https://www.us.elsevierhealth.com/fundamentals-of-nursing-9780443124068.html",
    "summary": "A foundational nursing textbook covering the nursing process, clinical reasoning, core skills and the scientific basis of everyday patient care. Long used in pre-registration nursing programmes, it is a standard reference for fundamental practice.",
    "keywords": [
      "nursing fundamentals",
      "nursing process",
      "clinical skills",
      "patient care"
    ],
    "divisions": [
      "nursing-allied-health"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "James K. Stoller"
      },
      {
        "name": "Albert J. Heuer"
      },
      {
        "name": "David L. Vines"
      },
      {
        "name": "Robert L. Chatburn"
      },
      {
        "name": "Eduardo Mireles-Cabodevila"
      }
    ],
    "slug": "egans-fundamentals-of-respiratory-care-13e",
    "title": "Egan's Fundamentals of Respiratory Care",
    "edition": "13th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2024,
    "isbn13": "9780323931991",
    "url": "https://shop.elsevier.com/books/egans-fundamentals-of-respiratory-care/stoller/978-0-323-93199-1",
    "summary": "The core textbook for respiratory therapy education, explaining the role of the respiratory therapist, the physiology behind respiratory treatment and its clinical application. It covers areas such as oxygen therapy, airway management and mechanical ventilation.",
    "keywords": [
      "respiratory therapy",
      "mechanical ventilation",
      "cardiopulmonary physiology",
      "airway management"
    ],
    "divisions": [
      "nursing-allied-health",
      "clinical-medicine"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "Laurence Brunton"
      },
      {
        "name": "Bjorn Knollmann"
      }
    ],
    "slug": "goodman-gilman-pharmacological-basis-therapeutics-14e",
    "title": "Goodman & Gilman's The Pharmacological Basis of Therapeutics",
    "edition": "14th edition",
    "category": "reference",
    "publisher": "McGraw-Hill Medical Publishing Division",
    "year": 2022,
    "isbn13": "9781264258079",
    "pages": 1664,
    "url": "https://openlibrary.org/books/OL38391864M",
    "summary": "The classic comprehensive pharmacology reference, describing how drugs act and how they are used in the context of physiology and disease. This edition adds chapters on topics including pharmacovigilance, the blood-brain barrier, cannabis, biological agents such as immune checkpoint inhibitors and CAR-T cells, and the gut microbiome.",
    "keywords": [
      "pharmacology",
      "therapeutics",
      "pharmacokinetics",
      "drug action",
      "pharmacovigilance"
    ],
    "divisions": [
      "pharmacology-natural-products",
      "clinical-medicine"
    ],
    "verifiedVia": "Open Library"
  },
  {
    "authors": [
      {
        "name": "James M. Ritter"
      },
      {
        "name": "Rod J. Flower"
      },
      {
        "name": "Graeme Henderson"
      },
      {
        "name": "Yoon Kong Loke"
      },
      {
        "name": "David MacEwan"
      },
      {
        "name": "Emma Robinson"
      },
      {
        "name": "James Fullerton"
      }
    ],
    "editors": [],
    "slug": "rang-dales-pharmacology-10e",
    "title": "Rang & Dale's Pharmacology",
    "edition": "10th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2023,
    "isbn13": "9780323873956",
    "pages": 872,
    "url": "https://www.us.elsevierhealth.com/rang-dales-pharmacology-9780323873956.html",
    "summary": "A widely adopted pharmacology textbook that explains drug mechanisms from molecular targets to clinical use, organised by body system and therapeutic area. The current edition adds material on newer modalities such as gene therapies, RNA-based drugs and personalised medicine.",
    "keywords": [
      "pharmacology",
      "drug mechanisms",
      "receptors",
      "therapeutics"
    ],
    "divisions": [
      "pharmacology-natural-products"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "John E. Hall"
      },
      {
        "name": "Michael E. Hall"
      }
    ],
    "editors": [],
    "slug": "guyton-hall-textbook-medical-physiology-15e",
    "title": "Guyton and Hall Textbook of Medical Physiology",
    "edition": "15th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2025,
    "isbn13": "9780443111013",
    "pages": 1200,
    "url": "https://www.us.elsevierhealth.com/guyton-and-hall-textbook-of-medical-physiology-9780443111013.html",
    "summary": "A long-standing physiology textbook explaining how the body's organ systems work and how their regulation fails in disease. It is a standard text for medical and health science students learning the physiological basis of clinical medicine.",
    "keywords": [
      "physiology",
      "organ systems",
      "homeostasis",
      "pathophysiology"
    ],
    "divisions": [
      "biomedical-sciences"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Vinay Kumar"
      },
      {
        "name": "Abul K. Abbas"
      },
      {
        "name": "Jon C. Aster"
      },
      {
        "name": "Andrea T Deyrup"
      }
    ],
    "editors": [],
    "slug": "robbins-kumar-basic-pathology-11e",
    "title": "Robbins & Kumar Basic Pathology",
    "edition": "11th edition",
    "category": "textbook",
    "publisher": "Elsevier",
    "year": 2022,
    "isbn13": "9780323790185",
    "pages": 840,
    "url": "https://www.us.elsevierhealth.com/robbins-kumar-basic-pathology-9780323790185.html",
    "summary": "A concise, heavily illustrated pathology textbook covering general disease processes such as inflammation, repair and neoplasia, and the pathology of individual organ systems. It links morphological changes to clinical presentation and is a core text in medical education.",
    "keywords": [
      "pathology",
      "disease mechanisms",
      "neoplasia",
      "inflammation"
    ],
    "divisions": [
      "biomedical-sciences",
      "clinical-medicine"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "Susan Standring",
        "role": "Editor"
      }
    ],
    "slug": "grays-anatomy-42e",
    "title": "Gray's Anatomy",
    "subtitle": "The Anatomical Basis of Clinical Practice",
    "edition": "42nd edition",
    "category": "reference",
    "publisher": "Elsevier",
    "year": 2021,
    "isbn13": "9780702077050",
    "pages": 1606,
    "url": "https://openlibrary.org/books/OL30190210M",
    "summary": "The classic comprehensive reference work on human anatomy, organised by body region and tying anatomical detail to clinical practice. It is used by clinicians, surgeons and biomedical scientists as an authoritative anatomical reference.",
    "keywords": [
      "anatomy",
      "clinical anatomy",
      "human body",
      "reference"
    ],
    "divisions": [
      "biomedical-sciences",
      "medical-illustration-visualization",
      "clinical-medicine"
    ],
    "verifiedVia": "Open Library"
  },
  {
    "authors": [],
    "editors": [
      {
        "name": "Julian P. T. Higgins",
        "role": "Editor"
      },
      {
        "name": "James Thomas",
        "role": "Editor"
      },
      {
        "name": "Jacqueline Chandler",
        "role": "Associate Editor"
      },
      {
        "name": "Miranda Cumpston",
        "role": "Associate Editor"
      },
      {
        "name": "Tianjing Li",
        "role": "Associate Editor"
      },
      {
        "name": "Matthew J. Page",
        "role": "Associate Editor"
      },
      {
        "name": "Vivian A. Welch",
        "role": "Associate Editor"
      }
    ],
    "slug": "cochrane-handbook-systematic-reviews-interventions-2e",
    "title": "Cochrane Handbook for Systematic Reviews of Interventions",
    "edition": "2nd edition",
    "category": "handbook",
    "publisher": "Wiley-Blackwell",
    "year": 2019,
    "isbn13": "9781119536628",
    "pages": 736,
    "url": "https://www.wiley.com/en-us/Cochrane+Handbook+for+Systematic+Reviews+of+Interventions%2C+2nd+Edition-p-9781119536628",
    "summary": "The official Cochrane guide to planning, conducting and reporting systematic reviews of the effects of healthcare interventions. It covers every stage from formulating the question and searching to risk-of-bias assessment, meta-analysis and GRADE-based interpretation, and is the core methods reference for review authors.",
    "keywords": [
      "systematic reviews",
      "meta-analysis",
      "Cochrane",
      "risk of bias",
      "evidence synthesis"
    ],
    "divisions": [
      "evidence-review-integrity",
      "research"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Michael Borenstein"
      },
      {
        "name": "Larry V. Hedges"
      },
      {
        "name": "Julian P. T. Higgins"
      },
      {
        "name": "Hannah R. Rothstein"
      }
    ],
    "editors": [],
    "slug": "introduction-to-meta-analysis-2e",
    "title": "Introduction to Meta-Analysis",
    "edition": "2nd edition",
    "category": "textbook",
    "publisher": "Wiley",
    "year": 2021,
    "isbn13": "9781119558354",
    "pages": 544,
    "url": "https://www.wiley.com/en-us/Introduction+to+Meta-Analysis%2C+2nd+Edition-p-9781119558354",
    "summary": "A conceptual introduction to the statistics of meta-analysis, explaining effect sizes, fixed-effect and random-effects models, heterogeneity and publication bias. It is written for researchers who need to understand and interpret meta-analyses without advanced mathematics.",
    "keywords": [
      "meta-analysis",
      "effect size",
      "heterogeneity",
      "random-effects model",
      "publication bias"
    ],
    "divisions": [
      "evidence-review-integrity",
      "research"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Frank H. Netter"
      }
    ],
    "editors": [],
    "slug": "netter-atlas-of-human-anatomy-8e",
    "title": "Netter Atlas of Human Anatomy",
    "subtitle": "Classic Regional Approach",
    "edition": "8th edition",
    "category": "atlas",
    "publisher": "Elsevier",
    "year": 2022,
    "isbn13": "9780323680424",
    "pages": 712,
    "url": "https://shop.elsevier.com/books/netter-atlas-of-human-anatomy-classic-regional-approach/netter/978-0-323-68042-4",
    "summary": "An atlas of human anatomy built around the hand-painted plates of physician-artist Frank H. Netter, arranged by body region. It is one of the best-known examples of medical illustration used in anatomy teaching and clinical reference.",
    "keywords": [
      "anatomy",
      "medical illustration",
      "atlas",
      "anatomical plates"
    ],
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences",
      "clinical-medicine"
    ],
    "verifiedVia": "Publisher page"
  },
  {
    "authors": [
      {
        "name": "Claus O. Wilke"
      }
    ],
    "editors": [],
    "slug": "fundamentals-of-data-visualization",
    "title": "Fundamentals of Data Visualization",
    "subtitle": "A Primer on Making Informative and Compelling Figures",
    "edition": "1st edition",
    "category": "handbook",
    "publisher": "O'Reilly Media",
    "year": 2019,
    "isbn13": "9781492031086",
    "pages": 390,
    "url": "https://clauswilke.com/dataviz/",
    "summary": "A practical guide to choosing and designing figures that represent data accurately, covering chart types, colour use, proportions, uncertainty and common pitfalls. A full version is freely readable online, making it a convenient reference for researchers preparing scientific figures.",
    "keywords": [
      "data visualization",
      "scientific figures",
      "colour",
      "chart design"
    ],
    "divisions": [
      "medical-illustration-visualization",
      "research"
    ],
    "verifiedVia": "Open Library"
  },
  {
    "authors": [
      {
        "name": "JAMA Network Editors"
      }
    ],
    "editors": [],
    "slug": "ama-manual-of-style-11e",
    "title": "AMA Manual of Style",
    "subtitle": "A Guide for Authors and Editors",
    "edition": "11th edition",
    "category": "reference",
    "publisher": "Oxford University Press",
    "year": 2020,
    "isbn13": "9780190246556",
    "pages": 1312,
    "url": "https://openlibrary.org/books/OL28060396M",
    "summary": "The style manual of the JAMA Network, covering manuscript preparation, references, ethical and legal issues in publishing, medical terminology, units and statistics. It is a standard reference for medical writers, authors and journal editors.",
    "keywords": [
      "style manual",
      "medical writing",
      "editing",
      "publication ethics",
      "references"
    ],
    "divisions": [
      "editorial-publications"
    ],
    "verifiedVia": "Open Library"
  },
  {
    "authors": [
      {
        "name": "Council of Science Editors"
      }
    ],
    "editors": [],
    "slug": "scientific-style-and-format-cse-8e",
    "title": "Scientific Style and Format",
    "subtitle": "The CSE Manual for Authors, Editors, and Publishers",
    "edition": "8th edition",
    "category": "reference",
    "publisher": "University of Chicago Press (in cooperation with the Council of Science Editors)",
    "year": 2014,
    "isbn13": "9780226116495",
    "pages": 840,
    "url": "https://openlibrary.org/books/OL28521083M",
    "summary": "The style manual of the Council of Science Editors, setting out conventions for scientific writing, nomenclature, symbols, numbers, citations and the publishing process across the sciences. It is widely used by journal editors and copyeditors to standardise scientific text.",
    "keywords": [
      "style manual",
      "scientific writing",
      "CSE",
      "editing",
      "citations"
    ],
    "divisions": [
      "editorial-publications"
    ],
    "verifiedVia": "Open Library"
  },
  {
    "authors": [
      {
        "name": "Barbara Gastel"
      },
      {
        "name": "Robert A. Day"
      }
    ],
    "editors": [],
    "slug": "how-to-write-and-publish-a-scientific-paper-9e",
    "title": "How to Write and Publish a Scientific Paper",
    "edition": "9th edition",
    "category": "handbook",
    "publisher": "Greenwood (ABC-CLIO)",
    "year": 2022,
    "isbn13": "9781440878824",
    "pages": 376,
    "url": "https://openlibrary.org/books/OL36280710M",
    "summary": "A long-established guide to preparing scientific papers, from structuring each section to choosing a journal, responding to peer review and handling ethical issues. Recent editions add guidance on open access, predatory journals and other aspects of modern publishing.",
    "keywords": [
      "scientific writing",
      "publishing",
      "peer review",
      "authorship"
    ],
    "divisions": [
      "editorial-publications",
      "research"
    ],
    "verifiedVia": "Open Library"
  }
];
