// Generated by scripts/import-library.mjs from verified source records. Edit the source JSON, not this file.
import type { Illustration } from '@/lib/illustrations';
import type { LearningResource } from '@/lib/education';

export const illustrationRecords: Illustration[] = [
  {
    "slug": "gray-490-heart-and-lungs-front-view",
    "title": "Heart and lungs, front view (Gray's Anatomy, plate 490)",
    "commonsFile": "File:Gray490.png",
    "description": "A classic engraved plate from Henry Gray's Anatomy of the Human Body (1918 edition), drawn by Henry Vandyke Carter. It shows the heart and lungs as seen from the front, a standard reference view for thoracic anatomy teaching.",
    "category": "anatomy",
    "creator": "Henry Vandyke Carter (Gray's Anatomy of the Human Body, 1918)",
    "license": "Public domain",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Gray490.png",
    "width": 600,
    "height": 585,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Gray490.png",
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences",
      "clinical-medicine"
    ]
  },
  {
    "slug": "animal-cell-structure",
    "title": "Structure of an animal cell",
    "commonsFile": "File:Animal cell structure en.svg",
    "description": "A labelled cutaway diagram of a typical animal cell drawn by LadyofHats (Mariana Ruiz). It identifies the major organelles, including the nucleus, mitochondria, endoplasmic reticulum and Golgi apparatus.",
    "category": "cellular",
    "creator": "LadyofHats (Mariana Ruiz)",
    "license": "Public domain",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Animal_cell_structure_en.svg/1280px-Animal_cell_structure_en.svg.png",
    "width": 1280,
    "height": 856,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Animal_cell_structure_en.svg",
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences"
    ]
  },
  {
    "slug": "dna-chemical-structure",
    "title": "Chemical structure of DNA",
    "commonsFile": "File:DNA chemical structure 2.svg",
    "description": "A chemical drawing of a short, four-base-pair stretch of the DNA double helix by Thomas Shafee. It shows how the sugar-phosphate backbones run in opposite directions and how the bases pair across the two strands.",
    "category": "molecular",
    "creator": "Thomas Shafee",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/DNA_chemical_structure_2.svg/1280px-DNA_chemical_structure_2.svg.png",
    "width": 1280,
    "height": 568,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:DNA_chemical_structure_2.svg",
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences"
    ]
  },
  {
    "slug": "afatinib-mechanism-of-action",
    "title": "Mechanism of action of afatinib",
    "commonsFile": "File:Afatinib mechanism.svg",
    "description": "A reaction scheme showing how the cancer drug afatinib attaches permanently to the epidermal growth factor receptor (EGFR). The drug forms a covalent bond with cysteine 797 of the receptor through a Michael addition.",
    "category": "molecular",
    "creator": "Anypodetos",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Afatinib_mechanism.svg/1280px-Afatinib_mechanism.svg.png",
    "width": 1280,
    "height": 450,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Afatinib_mechanism.svg",
    "divisions": [
      "medical-illustration-visualization",
      "pharmacology-natural-products",
      "biomedical-sciences"
    ]
  },
  {
    "slug": "synapse-agonist-vs-antagonist",
    "title": "Agonist versus antagonist at the synapse",
    "commonsFile": "File:Synapse Agonistvs Antagonist.png",
    "description": "An illustration by BruceBlaus contrasting how agonist and antagonist drugs act at receptors in a synapse. It is a useful teaching visual for basic receptor pharmacology.",
    "category": "molecular",
    "creator": "BruceBlaus",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/77/Synapse_Agonistvs_Antagonist.png",
    "width": 1200,
    "height": 730,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Synapse_Agonistvs_Antagonist.png",
    "divisions": [
      "medical-illustration-visualization",
      "pharmacology-natural-products",
      "biomedical-sciences"
    ]
  },
  {
    "slug": "blausen-tooth-anatomy",
    "title": "Tooth anatomy (Blausen Medical)",
    "commonsFile": "File:Blausen 0863 ToothAnatomy 02.png",
    "description": "A rendered cross-section of a tooth from the Blausen Medical gallery. It shows the internal structure of a tooth in a cutaway view.",
    "category": "dental",
    "creator": "BruceBlaus (Blausen Medical); cite as Blausen.com staff (2014), \"Medical gallery of Blausen Medical 2014\", WikiJournal of Medicine 1 (2), doi:10.15347/wjm/2014.010",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/Blausen_0863_ToothAnatomy_02.png/1280px-Blausen_0863_ToothAnatomy_02.png",
    "width": 1280,
    "height": 1280,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Blausen_0863_ToothAnatomy_02.png",
    "divisions": [
      "medical-illustration-visualization",
      "dentistry-oral-sciences"
    ]
  },
  {
    "slug": "human-molar-diagram",
    "title": "Diagram of a healthy human molar",
    "commonsFile": "File:Human tooth diagram-en.svg",
    "description": "A labelled vector diagram of a healthy molar by KDS4444. It marks the enamel, dentine, pulp and cementum together with the surrounding gum and bone.",
    "category": "dental",
    "creator": "KDS4444",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Human_tooth_diagram-en.svg/1280px-Human_tooth_diagram-en.svg.png",
    "width": 1280,
    "height": 1022,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Human_tooth_diagram-en.svg",
    "divisions": [
      "medical-illustration-visualization",
      "dentistry-oral-sciences"
    ]
  },
  {
    "slug": "blood-flow-through-the-heart",
    "title": "Blood flow through the heart",
    "commonsFile": "File:2101 Blood Flow Through the Heart.svg",
    "description": "An OpenStax Anatomy & Physiology figure, converted to vector form, tracing the path of blood through the chambers and valves of the heart. It separates the pulmonary and systemic circuits to show how blood is oxygenated and then sent to the body.",
    "category": "physiology",
    "creator": "OpenStax College",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/2101_Blood_Flow_Through_the_Heart.svg/1280px-2101_Blood_Flow_Through_the_Heart.svg.png",
    "width": 1280,
    "height": 869,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:2101_Blood_Flow_Through_the_Heart.svg",
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences",
      "clinical-medicine",
      "nursing-allied-health"
    ]
  },
  {
    "slug": "action-potential-myelinated-fibre",
    "title": "Action potential propagation along a myelinated nerve fibre",
    "commonsFile": "File:Propagation of action potential along myelinated nerve fiber en.svg",
    "description": "A schematic of how a nerve impulse travels along a myelinated axon of the peripheral nervous system, starting at the axon hillock. It shows the signal jumping between the unmyelinated gaps (nodes of Ranvier), known as saltatory conduction.",
    "category": "physiology",
    "creator": "Helixitta",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Propagation_of_action_potential_along_myelinated_nerve_fiber_en.svg/1280px-Propagation_of_action_potential_along_myelinated_nerve_fiber_en.svg.png",
    "width": 1280,
    "height": 736,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Propagation_of_action_potential_along_myelinated_nerve_fiber_en.svg",
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences"
    ]
  },
  {
    "slug": "coronary-stent-angioplasty",
    "title": "Stent placement in a coronary artery",
    "commonsFile": "File:Blausen 0034 Angioplasty Stent 01.png",
    "description": "A Blausen Medical illustration of a stent placed in a coronary artery during angioplasty. It shows how the expanded mesh tube holds a narrowed vessel open to restore blood flow.",
    "category": "procedural",
    "creator": "BruceBlaus (Blausen Medical); cite as Blausen.com staff (2014), \"Medical gallery of Blausen Medical 2014\", WikiJournal of Medicine 1 (2), doi:10.15347/wjm/2014.010",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Blausen_0034_Angioplasty_Stent_01.png",
    "width": 1024,
    "height": 768,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Blausen_0034_Angioplasty_Stent_01.png",
    "divisions": [
      "medical-illustration-visualization",
      "clinical-medicine"
    ]
  },
  {
    "slug": "nasogastric-intubation",
    "title": "Nasogastric intubation",
    "commonsFile": "File:Nasogastric Intubation.png",
    "description": "An illustration by BruceBlaus of a nasogastric tube passing through the nose and down the oesophagus into the stomach. It is suited to nursing and clinical skills teaching on tube placement.",
    "category": "procedural",
    "creator": "BruceBlaus",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/62/Nasogastric_Intubation.png",
    "width": 750,
    "height": 1500,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Nasogastric_Intubation.png",
    "divisions": [
      "medical-illustration-visualization",
      "nursing-allied-health",
      "clinical-medicine"
    ]
  },
  {
    "slug": "healthy-life-expectancy-world-by-sex",
    "title": "Healthy life expectancy worldwide, by sex",
    "commonsFile": "File:Healthy life expectancy bar chart -world -sex.png",
    "description": "A bar chart comparing global healthy life expectancy for men and women. The creator built it from data in the WHO Global Health Observatory.",
    "category": "infographic",
    "creator": "Lady3mlnm",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Healthy_life_expectancy_bar_chart_-world_-sex.png/1280px-Healthy_life_expectancy_bar_chart_-world_-sex.png",
    "width": 1280,
    "height": 442,
    "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Healthy_life_expectancy_bar_chart_-world_-sex.png",
    "divisions": [
      "medical-illustration-visualization",
      "clinical-medicine"
    ]
  }
];

export const resourceRecords: LearningResource[] = [
  {
    "slug": "cochrane-handbook",
    "title": "Cochrane Handbook for Systematic Reviews of Interventions",
    "provider": "Cochrane",
    "kind": "handbook",
    "access": "Free",
    "format": "Online reference",
    "description": "The official guide to how Cochrane systematic reviews of interventions are planned, run and reported. The current edition is version 6.5 (2024), edited by Julian Higgins and James Thomas, and it can be read online at no cost.",
    "url": "https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current",
    "divisions": [
      "evidence-review-integrity",
      "research"
    ]
  },
  {
    "slug": "equator-reporting-guidelines-library",
    "title": "EQUATOR Network reporting guideline library",
    "provider": "EQUATOR Network",
    "kind": "database",
    "access": "Free",
    "format": "Online reference",
    "description": "A searchable catalogue of more than 700 reporting guidelines for health research. You can filter it by study type, clinical area and report section to find the right checklist for a manuscript.",
    "url": "https://www.equator-network.org/reporting-guidelines/",
    "divisions": [
      "research",
      "evidence-review-integrity",
      "editorial-publications"
    ]
  },
  {
    "slug": "grade-handbook",
    "title": "GRADE Handbook",
    "provider": "GRADE Working Group",
    "kind": "handbook",
    "access": "Free",
    "format": "Online reference",
    "description": "A handbook by Schünemann, Brożek, Guyatt and Oxman on rating the certainty of evidence and the strength of recommendations with the GRADE approach. It was last updated in 2013 and, according to the page, is being replaced by the newer GRADE Book, but it remains available online.",
    "url": "https://gdt.gradepro.org/app/handbook/handbook.html",
    "divisions": [
      "evidence-review-integrity",
      "research",
      "clinical-medicine"
    ]
  },
  {
    "slug": "spirit-consort-2025",
    "title": "SPIRIT and CONSORT reporting guidelines (2025)",
    "provider": "SPIRIT–CONSORT Group",
    "kind": "guideline",
    "access": "Free",
    "format": "Online reference",
    "description": "The official home of the 2025 SPIRIT checklist for trial protocols and the 2025 CONSORT checklist for reporting randomised trial results. Checklists, explanation papers and free online writing aids can all be downloaded at no cost.",
    "url": "https://www.consort-spirit.org/",
    "divisions": [
      "research",
      "clinical-medicine",
      "editorial-publications",
      "evidence-review-integrity"
    ]
  },
  {
    "slug": "prisma-2020",
    "title": "PRISMA 2020 statement",
    "provider": "PRISMA Group",
    "kind": "guideline",
    "access": "Free",
    "format": "Online reference",
    "description": "The main reporting guideline for systematic reviews and meta-analyses. The site provides the checklist, the flow-diagram template, the explanation papers, extensions for other review types and translations.",
    "url": "https://www.prisma-statement.org/",
    "divisions": [
      "evidence-review-integrity",
      "research",
      "editorial-publications"
    ]
  },
  {
    "slug": "icmje-recommendations",
    "title": "ICMJE Recommendations for the Conduct, Reporting, Editing and Publication of Scholarly Work in Medical Journals",
    "provider": "International Committee of Medical Journal Editors (ICMJE)",
    "kind": "guideline",
    "access": "Free",
    "format": "Online reference",
    "description": "The widely adopted standards on authorship, conflicts of interest, peer review and publication ethics for medical journals. The latest version, updated January 2026, can be read online or downloaded as a PDF.",
    "url": "https://www.icmje.org/recommendations/",
    "divisions": [
      "editorial-publications",
      "evidence-review-integrity",
      "research"
    ]
  },
  {
    "slug": "tghn-ich-gcp-e6-r3",
    "title": "ICH Good Clinical Practice E6(R3)",
    "provider": "Global Health Training Centre (The Global Health Network)",
    "kind": "course",
    "access": "Free with registration",
    "format": "Self-paced online",
    "description": "An eight-module e-learning course, taking about three hours, on the updated ICH E6(R3) Good Clinical Practice guideline across the life of a trial. It is offered in English, Spanish, French and Portuguese, and learners who score at least 80% on the final quiz receive a certificate.",
    "url": "https://globalhealthtrainingcentre.tghn.org/ich-gcp-r3/",
    "divisions": [
      "research",
      "clinical-medicine",
      "nursing-allied-health",
      "evidence-review-integrity"
    ]
  },
  {
    "slug": "openwho",
    "title": "OpenWHO",
    "provider": "World Health Organization",
    "kind": "course",
    "access": "Free with registration",
    "format": "Self-paced online",
    "description": "WHO's open learning platform, with self-paced courses on outbreaks, emergency response, infection prevention and control, clinical management and other public health topics. The courses are multilingual, work on low bandwidth, and many offer a certificate.",
    "url": "https://openwho.org/",
    "divisions": [
      "clinical-medicine",
      "nursing-allied-health",
      "research"
    ]
  },
  {
    "slug": "who-imci-distance-learning",
    "title": "Integrated Management of Childhood Illness (IMCI) distance learning modules",
    "provider": "World Health Organization",
    "kind": "course",
    "access": "Free",
    "format": "PDF",
    "description": "A WHO self-study package from 2014 with nine modules on assessing and treating sick children, covering danger signs, cough, diarrhoea, fever, malnutrition, HIV and more. It also includes a facilitator guide, implementation guidance and a logbook.",
    "url": "https://www.who.int/publications/i/item/9789241506823",
    "divisions": [
      "clinical-medicine",
      "nursing-allied-health"
    ]
  },
  {
    "slug": "who-safe-surgery-guidelines",
    "title": "WHO Guidelines for Safe Surgery: Safe Surgery Saves Lives",
    "provider": "World Health Organization",
    "kind": "guideline",
    "access": "Free",
    "format": "PDF",
    "description": "WHO's 2009 guidance on patient safety in surgery, which supports the Safe Surgery Saves Lives initiative. The 124-page document can be downloaded free in several languages.",
    "url": "https://www.who.int/publications/i/item/9789241598552",
    "divisions": [
      "clinical-medicine",
      "nursing-allied-health"
    ]
  },
  {
    "slug": "openstax-anatomy-physiology-2e",
    "title": "Anatomy and Physiology 2e",
    "provider": "OpenStax (Rice University)",
    "kind": "textbook",
    "access": "Free",
    "format": "Online and PDF",
    "description": "An openly licensed (CC BY 4.0) two-semester textbook of human anatomy and physiology, organised by body system. It is free to read online or as a PDF, and its figures can be reused with attribution.",
    "url": "https://openstax.org/details/books/anatomy-and-physiology-2e",
    "divisions": [
      "biomedical-sciences",
      "nursing-allied-health",
      "medical-illustration-visualization"
    ]
  },
  {
    "slug": "nlm-pubmed-online-training",
    "title": "PubMed Online Training",
    "provider": "U.S. National Library of Medicine",
    "kind": "course",
    "access": "Free",
    "format": "Self-paced online",
    "description": "NLM's official training for searching PubMed, including short video quick tours, longer tutorials, on-demand classes and handouts. It is regularly updated, and some classes ask for free registration.",
    "url": "https://learn.nlm.nih.gov/documentation/training-packets/T0042010P/",
    "divisions": [
      "research",
      "evidence-review-integrity",
      "editorial-publications"
    ]
  },
  {
    "slug": "servier-medical-art",
    "title": "Servier Medical Art (SMART)",
    "provider": "Servier",
    "kind": "database",
    "access": "Free",
    "format": "Image library",
    "description": "A free library of more than 3,000 medical illustrations covering anatomy, physiology, pathology and treatment. The images are licensed CC BY 4.0, so they can be adapted for slides, posters, theses and articles with attribution.",
    "url": "https://smart.servier.com/",
    "divisions": [
      "medical-illustration-visualization",
      "biomedical-sciences",
      "editorial-publications"
    ]
  },
  {
    "slug": "fdi-oral-health-atlas",
    "title": "The Oral Health Atlas: The Challenge of Oral Disease – A call for global action (2nd edition)",
    "provider": "FDI World Dental Federation",
    "kind": "handbook",
    "access": "Free",
    "format": "PDF",
    "description": "FDI's 2015 atlas on the global burden of oral disease, covering caries, periodontal disease, oral cancer, risk factors, inequalities and prevention. It can be downloaded free in English, French and Spanish, and a free MOOC based on it is also available.",
    "url": "https://www.fdiworlddental.org/oral-health-atlas",
    "divisions": [
      "dentistry-oral-sciences",
      "research",
      "medical-illustration-visualization"
    ]
  }
];
