// Generated by scripts/import-library.mjs from verified source records. Edit the source JSON, not this file.
import type { StudyRecord } from '@/lib/research';

export const studyRecords: StudyRecord[] = [
  {
    "slug": "sprint-intensive-blood-pressure-control",
    "nctId": "NCT01206062",
    "title": "Systolic Blood Pressure Intervention Trial",
    "officialTitle": "Systolic Blood Pressure Intervention Trial",
    "registryStatus": "COMPLETED",
    "studyType": "INTERVENTIONAL",
    "design": "Randomized, parallel assignment, single-blind, primary purpose: treatment",
    "conditions": [
      "Hypertension"
    ],
    "interventions": [
      "Intensive control of SBP (drug)",
      "Standard control of SBP (drug)"
    ],
    "enrollment": 9361,
    "enrollmentType": "ACTUAL",
    "sponsor": "National Heart, Lung, and Blood Institute (NHLBI)",
    "collaborators": [
      "National Institute on Aging (NIA)",
      "National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK)",
      "National Institute of Neurological Disorders and Stroke (NINDS)",
      "Wake Forest University Health Sciences"
    ],
    "investigators": [
      {
        "name": "David M. Reboussin, PhD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Wake Forest University Health Sciences"
      },
      {
        "name": "Jackson T Wright, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Case Western Reserve University"
      },
      {
        "name": "Alfred Cheung, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Utah"
      },
      {
        "name": "Suzanne Oparil, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Alabama at Birmingham"
      },
      {
        "name": "Mike Rocco, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Wake Forest University Health Sciences"
      },
      {
        "name": "Bill Cushman, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Memphis VA Medical Center"
      }
    ],
    "startDate": "2010-10",
    "primaryCompletionDate": "2016-07",
    "completionDate": "2019-03",
    "lastUpdated": "2021-01-08",
    "countries": [
      "United States"
    ],
    "primaryOutcome": "Number of Participants With First Occurrence of a Myocardial Infarction (MI), Acute Coronary Syndrome (ACS), Stroke, Heart Failure (HF), or CVD Death",
    "objectives": [
      "Test whether aiming for a systolic blood pressure below 120 mmHg, rather than below 140 mmHg, lowers the risk of heart attack, stroke, heart failure and cardiovascular death.",
      "Compare the safety of intensive versus standard blood pressure treatment in adults at raised cardiovascular risk."
    ],
    "summary": "SPRINT was a large US multicentre randomised trial run by the NHLBI that compared two blood pressure targets in adults with hypertension. Participants were assigned either to an intensive systolic target or to the conventional target, and were followed for major cardiovascular events. Its main findings were published in the New England Journal of Medicine in 2015.",
    "resultsPublications": [
      {
        "citation": "SPRINT Research Group; Wright JT Jr, Williamson JD, Whelton PK, Snyder JK, Sink KM, Rocco MV, Reboussin DM, Rahman M, Oparil S, Lewis CE, Kimmel PL, Johnson KC, Goff DC Jr, Fine LJ, Cutler JA, Cushman WC, Cheung AK, Ambrosius WT. A Randomized Trial of Intensive versus Standard Blood-Pressure Control. N Engl J Med. 2015 Nov 26;373(22):2103-16. doi: 10.1056/NEJMoa1511939. Epub 2015 Nov 9.",
        "pmid": "26551272"
      }
    ],
    "hasResults": true,
    "divisions": [
      "clinical-medicine",
      "pharmacology-natural-products"
    ],
    "url": "https://clinicaltrials.gov/study/NCT01206062"
  },
  {
    "slug": "pocus-guided-diuretics-acute-heart-failure",
    "nctId": "NCT07469722",
    "title": "POcus INTERvention for Tailoring Diuretic Strategy in Acute Decompensated Heart Failure",
    "officialTitle": "Point-of-care Ultrasound Intervention for Tailoring Diuretic Strategy in Acute Decompensated Heart Failure",
    "registryStatus": "NOT_YET_RECRUITING",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE2/PHASE3",
    "design": "Randomized, parallel assignment, single-blind, primary purpose: treatment",
    "conditions": [
      "Acute Heart Failure (AHF)",
      "Congestive Heart Failure Acute",
      "Diuretic Effect",
      "Lung Ultrasonography Score",
      "Ultrasonography, Doppler",
      "Point-of-care Ultrasound (POCUS)"
    ],
    "interventions": [
      "Furosemide 40 Milligrams. (drug)",
      "Furosemide 40 Milligrams. (drug)",
      "Hydrochlorothiazide (HCTZ) 25 milligrams. (drug)",
      "Acetazolamide 250 milligrams. (drug)",
      "Dapagliflozin (10mg Tab) (drug)",
      "Potassium Chloride Oral Product (drug)"
    ],
    "enrollment": 128,
    "enrollmentType": "ESTIMATED",
    "sponsor": "Hospital de Clinicas de Porto Alegre",
    "collaborators": [],
    "investigators": [
      {
        "name": "Luis E Rohde, Professor",
        "role": "STUDY_CHAIR",
        "affiliation": "Hospital de Clinicas de Porto Alegre"
      }
    ],
    "startDate": "2026-03-23",
    "primaryCompletionDate": "2028-01-31",
    "completionDate": "2028-07-01",
    "lastUpdated": "2026-03-18",
    "countries": [
      "Brazil"
    ],
    "primaryOutcome": "Pairwise Comparisons With Wins of Clinical Benefit, a Composite of In-Hospital Mortality, Hospital Length of Stay, Absence of Congestion on DUCS at Discharge, and BNP Reduction From Admission to Day 7 or Discharge.",
    "objectives": [
      "Find out whether bedside ultrasound assessment of congestion can guide diuretic treatment better than usual care in acute decompensated heart failure.",
      "Compare a combined outcome of in-hospital death, length of stay, residual congestion and fall in BNP between the two strategies."
    ],
    "summary": "This Brazilian randomised trial will test whether a point-of-care ultrasound congestion score can be used to adjust diuretic therapy for people admitted with acute decompensated heart failure. Patients in the ultrasound-guided arm may receive stepped combinations of diuretics such as furosemide, hydrochlorothiazide, acetazolamide and dapagliflozin based on their scans. Outcomes are compared using a hierarchical win-ratio approach.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT07469722"
  },
  {
    "slug": "xylitol-gum-periodontal-disease-preterm-birth",
    "nctId": "NCT07424846",
    "title": "Xylitol and the Prevention of Periodontal Disease and Preterm Birth Trial",
    "officialTitle": "Xylitol and the Prevention of Periodontal Disease and Preterm Birth (XaPPP) Trial",
    "registryStatus": "RECRUITING",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE2/PHASE3",
    "design": "Randomized, parallel assignment, triple-blind, primary purpose: prevention",
    "conditions": [
      "Preterm Birth",
      "Low Birthweight Neonate",
      "Periodontitis",
      "Gingivitis",
      "Developmental Delay"
    ],
    "interventions": [
      "Xylitol Chewing gum (drug)",
      "Sorbitol chewing gum (other)"
    ],
    "enrollment": 6000,
    "enrollmentType": "ESTIMATED",
    "sponsor": "University of Washington",
    "collaborators": [
      "Baylor College of Medicine",
      "Baylor College of Medicine Children's Foundation",
      "Eunice Kennedy Shriver National Institute of Child Health and Human Development (NICHD)"
    ],
    "investigators": [
      {
        "name": "Greg Valentine",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Washington"
      }
    ],
    "startDate": "2026-03-26",
    "primaryCompletionDate": "2030-09-30",
    "completionDate": "2030-09-30",
    "lastUpdated": "2026-09-10",
    "countries": [
      "Malawi"
    ],
    "primaryOutcome": "Preterm Birth",
    "objectives": [
      "Determine whether chewing xylitol gum during pregnancy reduces preterm birth compared with a sorbitol control gum.",
      "Assess effects on maternal periodontal disease and gingivitis, birthweight and child development."
    ],
    "summary": "Building on an earlier cluster trial in Lilongwe, this Malawi-based randomised trial gives pregnant participants either xylitol-containing chewing gum or a sorbitol gum. The study asks whether improving maternal oral health with xylitol lowers rates of preterm birth and low birthweight. Child developmental outcomes are also tracked.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "dentistry-oral-sciences",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT07424846"
  },
  {
    "slug": "periodontal-treatment-heart-failure-biomarkers",
    "nctId": "NCT07036289",
    "title": "Periodontitis Treatment and Heart Failure",
    "officialTitle": "Effects Of PeriodontitisTtreatment On The Worsening Of Heart Failure: A Randomized Clinical Trial",
    "registryStatus": "ACTIVE_NOT_RECRUITING",
    "studyType": "INTERVENTIONAL",
    "design": "Randomized, parallel assignment, double-blind, primary purpose: treatment",
    "conditions": [
      "Heart Failure",
      "Periodontitis"
    ],
    "interventions": [
      "Mechanical Treatment (procedure)"
    ],
    "enrollment": 80,
    "enrollmentType": "ACTUAL",
    "sponsor": "University of Taubate",
    "collaborators": [
      "Federal University of Minas Gerais",
      "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
      "Fundação de Amparo à Pesquisa do Estado de São Paulo"
    ],
    "investigators": [
      {
        "name": "Jose R Cortelli, Doctorate",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Taubate"
      }
    ],
    "startDate": "2025-06-10",
    "primaryCompletionDate": "2025-12-30",
    "completionDate": "2026-12",
    "lastUpdated": "2026-02-13",
    "countries": [
      "Brazil"
    ],
    "primaryOutcome": "NT-proBNP in blood samples",
    "objectives": [
      "Measure whether scaling and root planing changes blood NT-proBNP levels in people with periodontitis and heart failure.",
      "Examine links between blood and saliva markers and heart failure severity, and track the immune response to a key oral bacterium."
    ],
    "summary": "This Brazilian study treats periodontitis with scaling and root planing in adults with and without heart failure, alongside a delayed-treatment control group. Researchers follow a cardiac marker (NT-proBNP) and oral and immune measures at three and six months. It explores whether gum treatment could have a measurable effect on heart failure.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "dentistry-oral-sciences",
      "biomedical-sciences"
    ],
    "url": "https://clinicaltrials.gov/study/NCT07036289"
  },
  {
    "slug": "diabetes-periodontal-therapy-trial-dptt",
    "nctId": "NCT00997178",
    "title": "Diabetes and Periodontal Therapy Trial",
    "officialTitle": "A Multicenter Randomized Single-Masked Clinical Trial Testing the Effect of Non-surgical Periodontal Therapy on Glycosylated Hemoglobin (HbA1c) Levels in Subjects With Type 2 Diabetes and Chronic Periodontitis",
    "registryStatus": "COMPLETED",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE3",
    "design": "Randomized, parallel assignment, single-blind, primary purpose: treatment",
    "conditions": [
      "Chronic Periodontitis",
      "Type 2 Diabetes"
    ],
    "interventions": [
      "Non-surgical periodontal therapy (procedure)",
      "Delayed non-surgical periodontal therapy (other)"
    ],
    "enrollment": 514,
    "enrollmentType": "ACTUAL",
    "sponsor": "Stony Brook University",
    "collaborators": [
      "University of Alabama at Birmingham",
      "University of Minnesota",
      "The University of Texas Health Science Center, Houston",
      "The University of Texas Health Science Center at San Antonio",
      "National Institute of Dental and Craniofacial Research (NIDCR)"
    ],
    "investigators": [
      {
        "name": "Steven Engebretson, DMD, MS, MS",
        "role": "STUDY_CHAIR",
        "affiliation": "Stony Brook University"
      },
      {
        "name": "Leslie Hyman, PhD",
        "role": "STUDY_DIRECTOR",
        "affiliation": "Stony Brook University"
      }
    ],
    "startDate": "2009-10",
    "primaryCompletionDate": "2012-10",
    "completionDate": "2012-12",
    "lastUpdated": "2014-01-20",
    "countries": [
      "United States"
    ],
    "primaryOutcome": "Change in Glycosylated Hemoglobin (HbA1c)",
    "objectives": [
      "Test whether non-surgical periodontal therapy lowers HbA1c at six months in people with type 2 diabetes and chronic periodontitis.",
      "Relate changes in gum health measures to changes in glucose control and insulin resistance."
    ],
    "summary": "DPTT was a multicentre US randomised trial in adults with type 2 diabetes and moderate-to-advanced periodontitis. One group received scaling, root planing and supportive periodontal care straight away, while the other had treatment delayed. The primary result, published in JAMA in 2013, examined the effect on HbA1c.",
    "resultsPublications": [
      {
        "citation": "Engebretson SP, Hyman LG, Michalowicz BS, Schoenfeld ER, Gelato MC, Hou W, Seaquist ER, Reddy MS, Lewis CE, Oates TW, Tripathy D, Katancik JA, Orlander PR, Paquette DW, Hanson NQ, Tsai MY. The effect of nonsurgical periodontal therapy on hemoglobin A1c levels in persons with type 2 diabetes and chronic periodontitis: a randomized clinical trial. JAMA. 2013 Dec 18;310(23):2523-32. doi: 10.1001/jama.2013.282431.",
        "pmid": "24346989"
      }
    ],
    "hasResults": false,
    "divisions": [
      "dentistry-oral-sciences",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT00997178"
  },
  {
    "slug": "smart-nurse-led-telemonitoring-complex-care",
    "nctId": "NCT05543720",
    "title": "Evaluation of Nurse-led Integrated Care of Complex Patients Facilitated By Telemonitoring: The SMaRT Study",
    "officialTitle": "Nurse-led Integrated Care of Complex Patients Facilitated By Telemonitoring: The Safe, Managed, and Responsive Transitions (SMaRT) Study",
    "registryStatus": "ACTIVE_NOT_RECRUITING",
    "studyType": "INTERVENTIONAL",
    "design": "Non-randomized, parallel assignment, open label, primary purpose: health services research",
    "conditions": [
      "Heart Failure，Congestive",
      "Mental Health (Depression)",
      "Diabetes Mellitus",
      "Chronic Obstructive Pulmonary Disease",
      "Hypertension"
    ],
    "interventions": [
      "Medly (device)"
    ],
    "enrollment": 350,
    "enrollmentType": "ESTIMATED",
    "sponsor": "University Health Network, Toronto",
    "collaborators": [
      "Markham Stouffville Hospital",
      "William Osler Health System",
      "Health Sciences North",
      "Women's College Hospital"
    ],
    "investigators": [
      {
        "name": "Emily Seto, PhD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Toronto"
      }
    ],
    "startDate": "2022-10-17",
    "primaryCompletionDate": "2026-12",
    "completionDate": "2026-12",
    "lastUpdated": "2026-06-01",
    "countries": [
      "Canada"
    ],
    "primaryOutcome": "Death and/or all-cause unplanned readmission",
    "objectives": [
      "Evaluate whether nurse-led integrated care supported by the Medly telemonitoring app reduces death or unplanned readmission at 30 days.",
      "Support coordinated care for people living with several chronic conditions such as heart failure, COPD, diabetes and hypertension."
    ],
    "summary": "The SMaRT study in Ontario, Canada, evaluates a model in which nurses coordinate the care of patients with multiple chronic conditions using home telemonitoring. Patients send home measurements through the Medly platform so the care team can spot problems between visits. The study compares early death and readmission outcomes with usual care.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "nursing-allied-health",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT05543720"
  },
  {
    "slug": "family-centred-pulmonary-rehabilitation-carers",
    "nctId": "NCT07791147",
    "title": "Family-centred Pulmonary Rehabilitation to Empower Carers",
    "officialTitle": "Family-centred Pulmonary Rehabilitation to Empower Carers",
    "registryStatus": "NOT_YET_RECRUITING",
    "studyType": "INTERVENTIONAL",
    "design": "Randomized, parallel assignment, single-blind, primary purpose: other",
    "conditions": [
      "Pulmonary Disease, Chronic Obstructive",
      "Lung Diseases, Interstitial",
      "Asthma",
      "Lung Neoplasms",
      "Bronchiectasis"
    ],
    "interventions": [
      "Carer inclusive pulmonary rehabilitation (behavioral)",
      "Pulmonary rehabilitation (behavioral)"
    ],
    "enrollment": 120,
    "enrollmentType": "ESTIMATED",
    "sponsor": "Aveiro University",
    "collaborators": [
      "Unidade Local de Saúde Matosinhos",
      "Unidade Local de Saúde Gaia/Espinho",
      "Unidade Local de Saúde da Região de Aveiro",
      "Unidade Local de Saúde do Baixo Mondego",
      "Unidade Local de Saúde Santa Maria",
      "Unidade Local de Saude Entre o Douro e Vouga"
    ],
    "startDate": "2026-09",
    "primaryCompletionDate": "2027-03",
    "completionDate": "2027-03",
    "lastUpdated": "2026-08-27",
    "countries": [
      "Portugal"
    ],
    "primaryOutcome": "Preparedness for caregiving scale",
    "objectives": [
      "Test whether including informal carers in pulmonary rehabilitation improves their preparedness for caregiving.",
      "Compare carer-inclusive pulmonary rehabilitation with standard pulmonary rehabilitation for people with chronic respiratory disease."
    ],
    "summary": "This Portuguese randomised trial, led by the University of Aveiro, will bring family members and other informal carers into pulmonary rehabilitation programmes alongside patients with chronic lung diseases. The comparison is against standard rehabilitation without carer involvement. The main outcome is carers' preparedness for caregiving after the programme.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "nursing-allied-health"
    ],
    "url": "https://clinicaltrials.gov/study/NCT07791147"
  },
  {
    "slug": "heart-camp-exercise-adherence-heart-failure",
    "nctId": "NCT01771900",
    "title": "Heart Failure Exercise And Resistance Training Camp (HEART Camp)",
    "officialTitle": "Heart Failure Exercise and Resistance Training CAMP",
    "registryStatus": "COMPLETED",
    "studyType": "INTERVENTIONAL",
    "design": "Randomized, parallel assignment, single-blind, primary purpose: prevention",
    "conditions": [
      "Heart Failure"
    ],
    "interventions": [
      "Heart Camp Group (behavioral)",
      "Attention Control Group (behavioral)"
    ],
    "enrollment": 42,
    "enrollmentType": "ACTUAL",
    "sponsor": "University of Nebraska",
    "collaborators": [
      "National Institute of Nursing Research (NINR)"
    ],
    "investigators": [
      {
        "name": "Bunny Pozehl, PhD, APRN-NP",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Nebraska"
      }
    ],
    "startDate": "2005-04-01",
    "primaryCompletionDate": "2007-12-26",
    "completionDate": "2007-12-26",
    "lastUpdated": "2023-09-01",
    "countries": [
      "United States"
    ],
    "primaryOutcome": "Adherence to Exercise",
    "objectives": [
      "Pilot a group-based training camp intervention that teaches people with heart failure to exercise and manage their own exercise over time.",
      "Check the feasibility of the intervention and the reliability of outcome measures, with exercise adherence as the main outcome."
    ],
    "summary": "HEART Camp was a nurse-led feasibility trial at the University of Nebraska, funded by the National Institute of Nursing Research. Participants with heart failure exercised in small groups guided by a nurse and an exercise physiologist, with support tapering off over six months to build self-management. Results were published in nursing and cardiopulmonary rehabilitation journals.",
    "resultsPublications": [
      {
        "citation": "Pozehl B, Duncan K, Hertzog M, Norman JF. Heart Failure Exercise And Training Camp: effects of a multicomponent exercise training intervention in patients with heart failure. Heart Lung. 2010 Nov-Dec;39(6 Suppl):S1-13. doi: 10.1016/j.hrtlng.2010.04.008. Epub 2010 Jul 3.",
        "pmid": "20598373"
      },
      {
        "citation": "Norman JF, Pozehl BJ, Duncan KA, Hertzog MA, Elokda AS, Krueger SK. Relationship of resting B-type natriuretic peptide level to cardiac work and total physical work capacity in heart failure patients. J Cardiopulm Rehabil Prev. 2009 Sep-Oct;29(5):310-3. doi: 10.1097/HCR.0b013e3181ac7bcb.",
        "pmid": "19561522"
      },
      {
        "citation": "Duncan K, Pozehl B, Norman JF, Hertzog M. A self-directed adherence management program for patients with heart failure completing combined aerobic and resistance exercise training. Appl Nurs Res. 2011 Nov;24(4):207-14. doi: 10.1016/j.apnr.2009.08.003. Epub 2009 Oct 15.",
        "pmid": "22099469"
      }
    ],
    "hasResults": false,
    "divisions": [
      "nursing-allied-health"
    ],
    "url": "https://clinicaltrials.gov/study/NCT01771900"
  },
  {
    "slug": "uganda-longitudinal-antimalarial-combinations",
    "nctId": "NCT00123552",
    "title": "Longitudinal Antimalarial Combinations in Uganda",
    "officialTitle": "Longitudinal Comparison of Combination Antimalarial Therapies in Ugandan Children: Evaluation of Safety, Tolerability, and Efficacy",
    "registryStatus": "COMPLETED",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE3",
    "design": "Randomized, parallel assignment, single-blind, primary purpose: treatment",
    "conditions": [
      "Malaria"
    ],
    "interventions": [
      "Amodiaquine+Artesunate (drug)",
      "Amodiaquine+Sulfadoxine/Pyrimethamine (drug)",
      "Artemether+Lumefantrine (drug)"
    ],
    "enrollment": 601,
    "enrollmentType": "ACTUAL",
    "sponsor": "University of California, San Francisco",
    "collaborators": [
      "National Institute of Allergy and Infectious Diseases (NIAID)"
    ],
    "startDate": "2004-11",
    "primaryCompletionDate": "2006-06",
    "completionDate": "2008-12",
    "lastUpdated": "2020-06-09",
    "countries": [
      "Uganda"
    ],
    "primaryOutcome": "Annual incidence of malaria per treatment arm",
    "objectives": [
      "Compare three combination treatments for uncomplicated malaria, including two artemisinin-based combinations, when used repeatedly in children.",
      "Measure the annual incidence of malaria in each treatment arm in a Kampala cohort."
    ],
    "summary": "This Phase 3 study followed a cohort of young children in Kampala, Uganda, treating each malaria episode with one of three randomised drug combinations: amodiaquine plus artesunate, amodiaquine plus sulfadoxine-pyrimethamine, or artemether-lumefantrine. Following children over time allowed comparison of efficacy and safety across repeated treatments. Several results papers are linked in the registry.",
    "resultsPublications": [
      {
        "citation": "Davis JC, Clark TD, Kemble SK, Talemwa N, Njama-Meya D, Staedke SG, Dorsey G. Longitudinal study of urban malaria in a cohort of Ugandan children: description of study site, census and recruitment. Malar J. 2006 Mar 21;5:18. doi: 10.1186/1475-2875-5-18.",
        "pmid": "16551365"
      },
      {
        "citation": "Njama-Meya D, Clark TD, Nzarubara B, Staedke S, Kamya MR, Dorsey G. Treatment of malaria restricted to laboratory-confirmed cases: a prospective cohort study in Ugandan children. Malar J. 2007 Jan 21;6:7. doi: 10.1186/1475-2875-6-7.",
        "pmid": "17239256"
      },
      {
        "citation": "Dorsey G, Staedke S, Clark TD, Njama-Meya D, Nzarubara B, Maiteki-Sebuguzi C, Dokomajilar C, Kamya MR, Rosenthal PJ. Combination therapy for uncomplicated falciparum malaria in Ugandan children: a randomized trial. JAMA. 2007 May 23;297(20):2210-9. doi: 10.1001/jama.297.20.2210.",
        "pmid": "17519410"
      },
      {
        "citation": "Clark TD, Greenhouse B, Njama-Meya D, Nzarubara B, Maiteki-Sebuguzi C, Staedke SG, Seto E, Kamya MR, Rosenthal PJ, Dorsey G. Factors determining the heterogeneity of malaria incidence in children in Kampala, Uganda. J Infect Dis. 2008 Aug 1;198(3):393-400. doi: 10.1086/589778.",
        "pmid": "18522503"
      },
      {
        "citation": "Maiteki-Sebuguzi C, Jagannathan P, Yau VM, Clark TD, Njama-Meya D, Nzarubara B, Talisuna AO, Kamya MR, Rosenthal PJ, Dorsey G, Staedke SG. Safety and tolerability of combination antimalarial therapies for uncomplicated falciparum malaria in Ugandan children. Malar J. 2008 Jun 11;7:106. doi: 10.1186/1475-2875-7-106.",
        "pmid": "18547415"
      },
      {
        "citation": "Staedke SG, Jagannathan P, Yeka A, Bukirwa H, Banek K, Maiteki-Sebuguzi C, Clark TD, Nzarubara B, Njama-Meya D, Mpimbaza A, Rosenthal PJ, Kamya MR, Wabwire-Mangen F, Dorsey G, Talisuna AO. Monitoring antimalarial safety and tolerability in clinical trials: a case study from Uganda. Malar J. 2008 Jun 11;7:107. doi: 10.1186/1475-2875-7-107.",
        "pmid": "18547416"
      },
      {
        "citation": "Greenhouse B, Slater M, Njama-Meya D, Nzarubara B, Maiteki-Sebuguzi C, Clark TD, Staedke SG, Kamya MR, Hubbard A, Rosenthal PJ, Dorsey G. Decreasing efficacy of antimalarial combination therapy in Uganda is explained by decreasing host immunity rather than increasing drug resistance. J Infect Dis. 2009 Mar 1;199(5):758-65. doi: 10.1086/596741.",
        "pmid": "19199542"
      },
      {
        "citation": "Clark TD, Njama-Meya D, Nzarubara B, Maiteki-Sebuguzi C, Greenhouse B, Staedke SG, Kamya MR, Dorsey G, Rosenthal PJ. Incidence of malaria and efficacy of combination antimalarial therapies over 4 years in an urban cohort of Ugandan children. PLoS One. 2010 Jul 30;5(7):e11759. doi: 10.1371/journal.pone.0011759.",
        "pmid": "20689585"
      }
    ],
    "hasResults": false,
    "divisions": [
      "pharmacology-natural-products",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT00123552"
  },
  {
    "slug": "piperaquine-pyronaridine-artesunate-pk-healthy-adults",
    "nctId": "NCT07470424",
    "title": "A Clinical Study of Piperaquine, Pyronaridine, and Artesunate Administered in Combination in Healthy Adults",
    "officialTitle": "A Randomized, Open-Label Crossover Study to Evaluate Potential Pharmacokinetic Interactions of Orally Administered Piperaquine, Pyronaridine and Artesunate in Healthy Adult Participants",
    "registryStatus": "NOT_YET_RECRUITING",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE1",
    "design": "Randomized, crossover assignment, open label, primary purpose: health services research",
    "conditions": [
      "Malaria"
    ],
    "interventions": [
      "Piperaquine (drug)",
      "Artesunate-pyronaridine (Pyramax) (drug)",
      "Piperaquine and artesunate-pyronaridine (Pyramax) (drug)"
    ],
    "enrollment": 24,
    "enrollmentType": "ESTIMATED",
    "sponsor": "University of Oxford",
    "collaborators": [],
    "startDate": "2026-11-01",
    "primaryCompletionDate": "2027-11-01",
    "completionDate": "2027-11-01",
    "lastUpdated": "2026-08-05",
    "countries": [
      "Thailand"
    ],
    "primaryOutcome": "Number of adverse events",
    "objectives": [
      "Assess the safety of combining piperaquine with pyronaridine-artesunate in healthy adults.",
      "Characterise the pharmacokinetics of each drug alone and in a triple combination."
    ],
    "summary": "This University of Oxford Phase 1 study in Thailand will give healthy adult volunteers three regimens in randomised sequence: piperaquine alone, pyronaridine-artesunate alone, and all three drugs together. Each course runs for three days with follow-up and washout periods between regimens. The aim is to understand how the drugs interact before wider use of triple artemisinin-based combinations.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "pharmacology-natural-products"
    ],
    "url": "https://clinicaltrials.gov/study/NCT07470424"
  },
  {
    "slug": "curcumin-retinal-amyloid-imaging",
    "nctId": "NCT05774704",
    "title": "Curcumin and Retinal Study",
    "officialTitle": "Curcumin and Retinal Amyloid-beta Pilot Study",
    "registryStatus": "RECRUITING",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE1/PHASE2",
    "design": "Randomized, parallel assignment, triple-blind, primary purpose: other",
    "conditions": [
      "Bioavailability",
      "Gut Microbiome",
      "Safety"
    ],
    "interventions": [
      "Low curcumin group (drug)",
      "High curcumin group (drug)"
    ],
    "enrollment": 60,
    "enrollmentType": "ESTIMATED",
    "sponsor": "Texas Tech University Health Sciences Center",
    "collaborators": [],
    "investigators": [
      {
        "name": "Chwan-Li (Leslie) Shen, PhD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Texas Tech University Health Sciences Center"
      }
    ],
    "startDate": "2023-08-21",
    "primaryCompletionDate": "2026-12-31",
    "completionDate": "2026-12-31",
    "lastUpdated": "2026-01-13",
    "countries": [
      "United States"
    ],
    "primaryOutcome": "Retinal imaging- amyloid fluorescent intensity",
    "objectives": [
      "Test whether two weeks of curcumin supplementation reaches the eye and binds amyloid beta, as seen on retinal imaging.",
      "Assess safety, bioavailability and changes in the gut microbiome at low and high curcumin doses."
    ],
    "summary": "This small randomised study at Texas Tech University Health Sciences Center gives participants either a low or a high dose of curcumin for two weeks. Retinal imaging is used to see whether curcumin crosses into nervous tissue and attaches to amyloid proteins. Researchers also look at safety, blood levels and gut bacteria.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "pharmacology-natural-products",
      "biomedical-sciences"
    ],
    "url": "https://clinicaltrials.gov/study/NCT05774704"
  },
  {
    "slug": "stroke-associated-pneumonia-prediction-biomarkers",
    "nctId": "NCT01079728",
    "title": "Prediction of Stroke-associated Pneumonia",
    "officialTitle": "Prediction of Stroke-associated Pneumonia",
    "registryStatus": "COMPLETED",
    "studyType": "OBSERVATIONAL",
    "design": "Case only observational study, prospective time perspective",
    "conditions": [
      "Ischemic Stroke"
    ],
    "enrollment": 486,
    "enrollmentType": "ACTUAL",
    "sponsor": "Charite University, Berlin, Germany",
    "collaborators": [
      "Siemens Health Care",
      "NeuroCure Clinical Research Center, Charite, Berlin"
    ],
    "investigators": [
      {
        "name": "Andreas Meisel, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Charite University Berlin (Center for Stroke Research Berlin CSB & NeuroCure Clinical Research Center NCRC)"
      },
      {
        "name": "Peter Heuschmann, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "Charité University Berlin (Center for Stroke Research Berlin CSB)"
      }
    ],
    "startDate": "2010-02",
    "primaryCompletionDate": "2013-01",
    "completionDate": "2013-04",
    "lastUpdated": "2022-01-04",
    "countries": [
      "Germany",
      "Spain"
    ],
    "primaryOutcome": "Predictive score for SAP based on clinical parameters assessed within 36h after stroke onset",
    "objectives": [
      "Develop and prospectively validate a clinical score to predict pneumonia in the first week after ischaemic stroke.",
      "Evaluate immune and infection-related blood markers for predicting and diagnosing stroke-associated pneumonia."
    ],
    "summary": "This prospective observational cohort, led by Charité Berlin with sites in Germany and Spain, followed patients after acute ischaemic stroke. It combined clinical information with measurements of immune function and inflammation to see who goes on to develop pneumonia. Several papers on prediction scores and biomarkers such as IL-6 have come from the cohort.",
    "resultsPublications": [
      {
        "citation": "Hoffmann S, Harms H, Ulm L, Nabavi DG, Mackert BM, Schmehl I, Jungehulsing GJ, Montaner J, Bustamante A, Hermans M, Hamilton F, Gohler J, Malzahn U, Malsch C, Heuschmann PU, Meisel C, Meisel A; PREDICT Investigators. Stroke-induced immunodepression and dysphagia independently predict stroke-associated pneumonia - The PREDICT study. J Cereb Blood Flow Metab. 2017 Dec;37(12):3671-3682. doi: 10.1177/0271678X16671964. Epub 2016 Oct 14.",
        "pmid": "27733675"
      },
      {
        "citation": "Hotter B, Hoffmann S, Ulm L, Meisel C, Bustamante A, Montaner J, Katan M, Smith CJ, Meisel A. External Validation of Five Scores to Predict Stroke-Associated Pneumonia and the Role of Selected Blood Biomarkers. Stroke. 2021 Jan;52(1):325-330. doi: 10.1161/STROKEAHA.120.031884. Epub 2020 Dec 7.",
        "pmid": "33280547"
      },
      {
        "citation": "Hotter B, Hoffmann S, Ulm L, Meisel C, Fiebach JB, Meisel A. IL-6 Plasma Levels Correlate With Cerebral Perfusion Deficits and Infarct Sizes in Stroke Patients Without Associated Infections. Front Neurol. 2019 Feb 15;10:83. doi: 10.3389/fneur.2019.00083. eCollection 2019.",
        "pmid": "30828313"
      },
      {
        "citation": "Hotter B, Hoffmann S, Ulm L, Montaner J, Bustamante A, Meisel C, Meisel A. Inflammatory and stress markers predicting pneumonia, outcome, and etiology in patients with stroke: Biomarkers for predicting pneumonia, functional outcome, and death after stroke. Neurol Neuroimmunol Neuroinflamm. 2020 Feb 25;7(3):e692. doi: 10.1212/NXI.0000000000000692. Print 2020 May.",
        "pmid": "32098866"
      },
      {
        "citation": "Mengel A, Ulm L, Hotter B, Harms H, Piper SK, Grittner U, Montaner J, Meisel C, Meisel A, Hoffmann S. Biomarkers of immune capacity, infection and inflammation are associated with poor outcome and mortality after stroke - the PREDICT study. BMC Neurol. 2019 Jul 3;19(1):148. doi: 10.1186/s12883-019-1375-6.",
        "pmid": "31269910"
      },
      {
        "citation": "Winek K, Lobentanzer S, Nadorp B, Dubnov S, Dames C, Jagdmann S, Moshitzky G, Hotter B, Meisel C, Greenberg DS, Shifman S, Klein J, Shenhar-Tsarfaty S, Meisel A, Soreq H. Transfer RNA fragments replace microRNA regulators of the cholinergic poststroke immune blockade. Proc Natl Acad Sci U S A. 2020 Dec 22;117(51):32606-32616. doi: 10.1073/pnas.2013542117. Epub 2020 Dec 7.",
        "pmid": "33288717"
      }
    ],
    "hasResults": false,
    "divisions": [
      "biomedical-sciences",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT01079728"
  },
  {
    "slug": "dallas-2k-depression-biosignatures",
    "nctId": "NCT02919280",
    "title": "Dallas 2K: A Natural History Study of Depression",
    "officialTitle": "Dallas 2K: A Natural History Study of Depression",
    "registryStatus": "ACTIVE_NOT_RECRUITING",
    "studyType": "OBSERVATIONAL",
    "design": "Cohort observational study, prospective time perspective",
    "conditions": [
      "Depression",
      "Depression, Bipolar"
    ],
    "interventions": [
      "Observational Study (other)"
    ],
    "enrollment": 2500,
    "enrollmentType": "ESTIMATED",
    "sponsor": "University of Texas Southwestern Medical Center",
    "collaborators": [],
    "investigators": [
      {
        "name": "Madhukar Trivedi, MD",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Texas Southwestern Medical Center"
      }
    ],
    "startDate": "2016-06-14",
    "primaryCompletionDate": "2036-09",
    "completionDate": "2036-09",
    "lastUpdated": "2026-09-15",
    "countries": [
      "United States"
    ],
    "primaryOutcome": "Longitudinal changes in depression severity of subjects with elevated symptomatology on Patient Health Questionnaire (PHQ-9) for non-psychotic depressive disorders.",
    "objectives": [
      "Identify and validate biological signatures that predict treatment response and outcomes in depression.",
      "Follow changes in depression severity over time using questionnaires, blood biomarkers, genomics, brain imaging and EEG."
    ],
    "summary": "Dallas 2K is a long-term observational cohort at UT Southwestern that follows people with elevated depressive symptoms. Participants contribute clinical, lifestyle, blood, genetic, neuroimaging and EEG data so researchers can look for markers linked to recovery. Follow-up is planned to continue into the 2030s.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "biomedical-sciences"
    ],
    "url": "https://clinicaltrials.gov/study/NCT02919280"
  },
  {
    "slug": "recovery-platform-trial",
    "nctId": "NCT04381936",
    "title": "Randomised Evaluation of COVID-19 Therapy",
    "officialTitle": "Randomised Evaluation of COVID-19 Therapy",
    "registryStatus": "RECRUITING",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE3",
    "design": "Randomized, factorial assignment, open label, primary purpose: treatment",
    "conditions": [
      "Pneumonia"
    ],
    "interventions": [
      "Lopinavir-Ritonavir (drug)",
      "Corticosteroid (drug)",
      "Hydroxychloroquine (drug)",
      "Azithromycin (drug)",
      "Convalescent plasma (biological)",
      "Tocilizumab (drug)",
      "Immunoglobulin (biological)",
      "Synthetic neutralising antibodies (drug)",
      "Aspirin (drug)",
      "Colchicine (drug)",
      "Baricitinib (drug)",
      "Anakinra (drug)",
      "Dimethyl fumarate (drug)",
      "High Dose Corticosteroid (drug)",
      "Empagliflozin (drug)",
      "Sotrovimab (drug)",
      "Molnupiravir (drug)",
      "Paxlovid (drug)",
      "Baloxavir Marboxil (drug)",
      "Oseltamivir (drug)",
      "Corticosteroids (dexamethasone) (drug)",
      "Corticosteroids (dexamethasone) (drug)"
    ],
    "enrollment": 70000,
    "enrollmentType": "ESTIMATED",
    "sponsor": "University of Oxford",
    "collaborators": [
      "UK Research and Innovation",
      "National Institute for Health Research, United Kingdom",
      "Wellcome Trust",
      "Bill and Melinda Gates Foundation",
      "Department for International Development, United Kingdom",
      "Health Data Research UK",
      "Medical Research Council Population Health Research Unit",
      "NIHR Health Protection Research Unit in Emerging and Zoonotic Infections",
      "Flu Lab"
    ],
    "investigators": [
      {
        "name": "Peter W Horby",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "University of Oxford"
      }
    ],
    "startDate": "2020-03-19",
    "primaryCompletionDate": "2028-09-30",
    "completionDate": "2038-09-30",
    "lastUpdated": "2026-04-21",
    "countries": [
      "United Kingdom",
      "Belgium",
      "Estonia",
      "France",
      "Ghana",
      "India",
      "Indonesia",
      "Italy"
    ],
    "primaryOutcome": "Community-acquired pneumonia: All-cause mortality (with subsidiary analyses of cause of death and of death at various timepoints following discharge)",
    "objectives": [
      "Evaluate multiple treatments in parallel within one adaptive platform to find which reduce death in patients hospitalised with pneumonia.",
      "Extend the platform from COVID-19 to influenza and community-acquired pneumonia."
    ],
    "summary": "RECOVERY is a large randomised, open-label platform trial led by the University of Oxford that has tested many treatments for patients admitted to hospital with COVID-19, and has since added influenza and community-acquired pneumonia. Its pragmatic design, with minimal data collection and a shared control group, allowed rapid answers, including the finding that dexamethasone reduced deaths. It remains a reference model for efficient trial methodology.",
    "resultsPublications": [
      {
        "citation": "RECOVERY Collaborative Group. Aspirin in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet. 2022 Jan 8;399(10320):143-151. doi: 10.1016/S0140-6736(21)01825-0. Epub 2021 Nov 17.",
        "pmid": "34800427"
      },
      {
        "citation": "RECOVERY Collaborative Group. Lopinavir-ritonavir in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet. 2020 Oct 24;396(10259):1345-1352. doi: 10.1016/S0140-6736(20)32013-4. Epub 2020 Oct 5.",
        "pmid": "33031764"
      },
      {
        "citation": "RECOVERY Collaborative Group. Colchicine in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet Respir Med. 2021 Dec;9(12):1419-1426. doi: 10.1016/S2213-2600(21)00435-5. Epub 2021 Oct 18.",
        "pmid": "34672950"
      },
      {
        "citation": "RECOVERY Collaborative Group; Horby P, Lim WS, Emberson JR, Mafham M, Bell JL, Linsell L, Staplin N, Brightling C, Ustianowski A, Elmahi E, Prudon B, Green C, Felton T, Chadwick D, Rege K, Fegan C, Chappell LC, Faust SN, Jaki T, Jeffery K, Montgomery A, Rowan K, Juszczak E, Baillie JK, Haynes R, Landray MJ. Dexamethasone in Hospitalized Patients with Covid-19. N Engl J Med. 2021 Feb 25;384(8):693-704. doi: 10.1056/NEJMoa2021436. Epub 2020 Jul 17.",
        "pmid": "32678530"
      },
      {
        "citation": "RECOVERY Collaborative Group; Horby P, Mafham M, Linsell L, Bell JL, Staplin N, Emberson JR, Wiselka M, Ustianowski A, Elmahi E, Prudon B, Whitehouse T, Felton T, Williams J, Faccenda J, Underwood J, Baillie JK, Chappell LC, Faust SN, Jaki T, Jeffery K, Lim WS, Montgomery A, Rowan K, Tarning J, Watson JA, White NJ, Juszczak E, Haynes R, Landray MJ. Effect of Hydroxychloroquine in Hospitalized Patients with Covid-19. N Engl J Med. 2020 Nov 19;383(21):2030-2040. doi: 10.1056/NEJMoa2022926. Epub 2020 Oct 8.",
        "pmid": "33031652"
      },
      {
        "citation": "RECOVERY Collaborative Group. Azithromycin in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet. 2021 Feb 13;397(10274):605-612. doi: 10.1016/S0140-6736(21)00149-5. Epub 2021 Feb 2.",
        "pmid": "33545096"
      },
      {
        "citation": "RECOVERY Collaborative Group. Tocilizumab in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet. 2021 May 1;397(10285):1637-1645. doi: 10.1016/S0140-6736(21)00676-0.",
        "pmid": "33933206"
      },
      {
        "citation": "RECOVERY Collaborative Group. Convalescent plasma in patients admitted to hospital with COVID-19 (RECOVERY): a randomised controlled, open-label, platform trial. Lancet. 2021 May 29;397(10289):2049-2059. doi: 10.1016/S0140-6736(21)00897-7. Epub 2021 May 14.",
        "pmid": "34000257"
      },
      {
        "citation": "RECOVERY Collaborative Group. Casirivimab and imdevimab in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet. 2022 Feb 12;399(10325):665-676. doi: 10.1016/S0140-6736(22)00163-5.",
        "pmid": "35151397"
      },
      {
        "citation": "RECOVERY Collaborative Group. Baricitinib in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial and updated meta-analysis. Lancet. 2022 Jul 30;400(10349):359-368. doi: 10.1016/S0140-6736(22)01109-6.",
        "pmid": "35908569"
      },
      {
        "citation": "RECOVERY Collaborative Group. Electronic address: recoverytrial@ndph.ox.ac.uk; RECOVERY Collaborative Group. Higher dose corticosteroids in patients admitted to hospital with COVID-19 who are hypoxic but not requiring ventilatory support (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet. 2023 May 6;401(10387):1499-1507. doi: 10.1016/S0140-6736(23)00510-X. Epub 2023 Apr 13.",
        "pmid": "37060915"
      },
      {
        "citation": "RECOVERY Collaborative Group. Empagliflozin in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet Diabetes Endocrinol. 2023 Dec;11(12):905-914. doi: 10.1016/S2213-8587(23)00253-X. Epub 2023 Oct 18.",
        "pmid": "37865101"
      },
      {
        "citation": "RECOVERY Collaborative Group; Horby PW, Peto L, Staplin N, Campbell M, Pessoa-Amorim G, Mafham M, Emberson JR, Stewart R, Prudon B, Uriel A, Green CA, Dhasmana DJ, Malein F, Majumdar J, Collini P, Shurmer J, Yates B, Baillie JK, Buch MH, Day J, Faust SN, Jaki T, Jeffery K, Juszczak E, Knight M, Lim WS, Montgomery A, Mumford A, Rowan K, Thwaites G, Haynes R, Landray MJ. Dimethyl fumarate in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Nat Commun. 2024 Jan 31;15(1):924. doi: 10.1038/s41467-023-43644-x.",
        "pmid": "38296965"
      },
      {
        "citation": "RECOVERY Collaborative Group. Molnupiravir or nirmatrelvir-ritonavir plus usual care versus usual care alone in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet Infect Dis. 2025 Sep;25(9):1000-1010. doi: 10.1016/S1473-3099(25)00093-3. Epub 2025 May 15.",
        "pmid": "40383127"
      },
      {
        "citation": "RECOVERY Collaborative Group. Sotrovimab versus usual care in patients admitted to hospital with COVID-19 (RECOVERY): a randomised, controlled, open-label, platform trial. Lancet Infect Dis. 2026 Jan;26(1):34-45. doi: 10.1016/S1473-3099(25)00361-5. Epub 2025 Aug 28.",
        "pmid": "40886716"
      }
    ],
    "hasResults": false,
    "divisions": [
      "research",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT04381936"
  },
  {
    "slug": "wheat-boost-video-consent-swat",
    "nctId": "NCT07284329",
    "title": "Examining the Efficacy of a Digital Media Intervention to Increase Recruitment Rates",
    "officialTitle": "Examining the Efficacy of a Parent-targeted Co-designed Digital Media Intervention to Increase Recruitment Rates Across a Multi-site Randomized Clinical Trial in Canadian NICU's",
    "registryStatus": "RECRUITING",
    "studyType": "INTERVENTIONAL",
    "design": "Randomized, parallel assignment, open label, primary purpose: other",
    "conditions": [
      "Consent Process"
    ],
    "interventions": [
      "Intervention (Video) Arm (behavioral)"
    ],
    "enrollment": 787,
    "enrollmentType": "ESTIMATED",
    "sponsor": "IWK Health Centre",
    "collaborators": [],
    "investigators": [
      {
        "name": "Balpreet Singh",
        "role": "PRINCIPAL_INVESTIGATOR",
        "affiliation": "IWK Health"
      }
    ],
    "startDate": "2025-01-06",
    "primaryCompletionDate": "2026-04-15",
    "completionDate": "2026-04-30",
    "lastUpdated": "2025-12-16",
    "countries": [
      "Canada"
    ],
    "primaryOutcome": "Opt-in Rate for the WHEAT International Trial",
    "objectives": [
      "Test whether a short digital video increases the proportion of families who agree to join a neonatal trial.",
      "Improve how information about research is shared with parents in neonatal intensive care."
    ],
    "summary": "WHEAT-Boost is a Study Within A Trial embedded in the WHEAT International Trial in Canadian neonatal units. Families approached about the host trial are randomised to receive a video-based explanation or the usual information. The main measure is the opt-in rate to the host trial.",
    "resultsPublications": [],
    "hasResults": false,
    "divisions": [
      "research",
      "nursing-allied-health"
    ],
    "url": "https://clinicaltrials.gov/study/NCT07284329"
  },
  {
    "slug": "stampede-multi-arm-multi-stage-prostate-cancer",
    "nctId": "NCT00268476",
    "title": "Systemic Therapy in Advancing or Metastatic Prostate Cancer: Evaluation of Drug Efficacy",
    "officialTitle": "STAMPEDE: Systemic Therapy in Advancing or Metastatic Prostate Cancer: Evaluation of Drug Efficacy: A Multi-Stage Multi-Arm Randomised Controlled Trial",
    "registryStatus": "ACTIVE_NOT_RECRUITING",
    "studyType": "INTERVENTIONAL",
    "phase": "PHASE2/PHASE3",
    "design": "Randomized, parallel assignment, open label, primary purpose: treatment",
    "conditions": [
      "Prostate Cancer"
    ],
    "interventions": [
      "Celecoxib (drug)",
      "Docetaxel (drug)",
      "Prednisolone (drug)",
      "ADT (drug)",
      "Zoledronic Acid (drug)",
      "Abiraterone (drug)",
      "Radiotherapy to the prostate (radiation)",
      "Enzalutamide (drug)",
      "Metformin (drug)",
      "Transdermal Oestradiol (drug)"
    ],
    "enrollment": 11992,
    "enrollmentType": "ACTUAL",
    "sponsor": "Medical Research Council",
    "collaborators": [],
    "investigators": [
      {
        "name": "Nicholas D. James, MD",
        "role": "STUDY_CHAIR",
        "affiliation": "Institute of Cancer Research, United Kingdom"
      }
    ],
    "startDate": "2005-07-08",
    "primaryCompletionDate": "2026-03",
    "completionDate": "2030-12",
    "lastUpdated": "2023-04-18",
    "countries": [
      "Switzerland",
      "United Kingdom"
    ],
    "primaryOutcome": "Overall survival",
    "objectives": [
      "Assess whether adding new treatments to standard hormone therapy improves survival in men starting long-term androgen deprivation for prostate cancer.",
      "Use a multi-arm, multi-stage design to compare many treatment approaches against a shared control arm."
    ],
    "summary": "STAMPEDE is a long-running UK-led platform trial in men with high-risk or metastatic hormone-naive prostate cancer. It has used a multi-arm, multi-stage design to test additions such as docetaxel, abiraterone, zoledronic acid and radiotherapy against standard care, with overall survival as its main outcome. It is widely cited as an example of efficient adaptive trial methodology.",
    "resultsPublications": [
      {
        "citation": "James ND, Sydes MR, Clarke NW, Mason MD, Dearnaley DP, Anderson J, Popert RJ, Sanders K, Morgan RC, Stansfeld J, Dwyer J, Masters J, Parmar MK. Systemic therapy for advancing or metastatic prostate cancer (STAMPEDE): a multi-arm, multistage randomized controlled trial. BJU Int. 2009 Feb;103(4):464-9. doi: 10.1111/j.1464-410X.2008.08034.x. Epub 2008 Oct 8.",
        "pmid": "18990168"
      },
      {
        "citation": "James ND, Sydes MR, Mason MD, Clarke NW, Anderson J, Dearnaley DP, Dwyer J, Jovic G, Ritchie AW, Russell JM, Sanders K, Thalmann GN, Bertelli G, Birtle AJ, O'Sullivan JM, Protheroe A, Sheehan D, Srihari N, Parmar MK; STAMPEDE investigators. Celecoxib plus hormone therapy versus hormone therapy alone for hormone-sensitive prostate cancer: first results from the STAMPEDE multiarm, multistage, randomised controlled trial. Lancet Oncol. 2012 May;13(5):549-58. doi: 10.1016/S1470-2045(12)70088-8. Epub 2012 Mar 26.",
        "pmid": "22452894"
      },
      {
        "citation": "Vale CL, Burdett S, Rydzewska LHM, Albiges L, Clarke NW, Fisher D, Fizazi K, Gravis G, James ND, Mason MD, Parmar MKB, Sweeney CJ, Sydes MR, Tombal B, Tierney JF; STOpCaP Steering Group. Addition of docetaxel or bisphosphonates to standard of care in men with localised or metastatic, hormone-sensitive prostate cancer: a systematic review and meta-analyses of aggregate data. Lancet Oncol. 2016 Feb;17(2):243-256. doi: 10.1016/S1470-2045(15)00489-1. Epub 2015 Dec 21.",
        "pmid": "26718929"
      },
      {
        "citation": "Mason MD, Clarke NW, James ND, Dearnaley DP, Spears MR, Ritchie AWS, Attard G, Cross W, Jones RJ, Parker CC, Russell JM, Thalmann GN, Schiavone F, Cassoly E, Matheson D, Millman R, Rentsch CA, Barber J, Gilson C, Ibrahim A, Logue J, Lydon A, Nikapota AD, O'Sullivan JM, Porfiri E, Protheroe A, Srihari NN, Tsang D, Wagstaff J, Wallace J, Walmsley C, Parmar MKB, Sydes MR; STAMPEDE Investigators. Adding Celecoxib With or Without Zoledronic Acid for Hormone-Naive Prostate Cancer: Long-Term Survival Results From an Adaptive, Multiarm, Multistage, Platform, Randomized Controlled Trial. J Clin Oncol. 2017 May 10;35(14):1530-1541. doi: 10.1200/JCO.2016.69.0677. Epub 2017 Mar 13.",
        "pmid": "28300506"
      },
      {
        "citation": "James ND, de Bono JS, Spears MR, Clarke NW, Mason MD, Dearnaley DP, Ritchie AWS, Amos CL, Gilson C, Jones RJ, Matheson D, Millman R, Attard G, Chowdhury S, Cross WR, Gillessen S, Parker CC, Russell JM, Berthold DR, Brawley C, Adab F, Aung S, Birtle AJ, Bowen J, Brock S, Chakraborti P, Ferguson C, Gale J, Gray E, Hingorani M, Hoskin PJ, Lester JF, Malik ZI, McKinna F, McPhail N, Money-Kyrle J, O'Sullivan J, Parikh O, Protheroe A, Robinson A, Srihari NN, Thomas C, Wagstaff J, Wylie J, Zarkar A, Parmar MKB, Sydes MR; STAMPEDE Investigators. Abiraterone for Prostate Cancer Not Previously Treated with Hormone Therapy. N Engl J Med. 2017 Jul 27;377(4):338-351. doi: 10.1056/NEJMoa1702900. Epub 2017 Jun 3.",
        "pmid": "28578639"
      },
      {
        "citation": "Sydes MR, Spears MR, Mason MD, Clarke NW, Dearnaley DP, de Bono JS, Attard G, Chowdhury S, Cross W, Gillessen S, Malik ZI, Jones R, Parker CC, Ritchie AWS, Russell JM, Millman R, Matheson D, Amos C, Gilson C, Birtle A, Brock S, Capaldi L, Chakraborti P, Choudhury A, Evans L, Ford D, Gale J, Gibbs S, Gilbert DC, Hughes R, McLaren D, Lester JF, Nikapota A, O'Sullivan J, Parikh O, Peedell C, Protheroe A, Rudman SM, Shaffer R, Sheehan D, Simms M, Srihari N, Strebel R, Sundar S, Tolan S, Tsang D, Varughese M, Wagstaff J, Parmar MKB, James ND; STAMPEDE Investigators. Adding abiraterone or docetaxel to long-term hormone therapy for prostate cancer: directly randomised data from the STAMPEDE multi-arm, multi-stage platform protocol. Ann Oncol. 2018 May 1;29(5):1235-1248. doi: 10.1093/annonc/mdy072.",
        "pmid": "29529169"
      },
      {
        "citation": "Parker CC, James ND, Brawley CD, Clarke NW, Hoyle AP, Ali A, Ritchie AWS, Attard G, Chowdhury S, Cross W, Dearnaley DP, Gillessen S, Gilson C, Jones RJ, Langley RE, Malik ZI, Mason MD, Matheson D, Millman R, Russell JM, Thalmann GN, Amos CL, Alonzi R, Bahl A, Birtle A, Din O, Douis H, Eswar C, Gale J, Gannon MR, Jonnada S, Khaksar S, Lester JF, O'Sullivan JM, Parikh OA, Pedley ID, Pudney DM, Sheehan DJ, Srihari NN, Tran ATH, Parmar MKB, Sydes MR; Systemic Therapy for Advanced or Metastatic Prostate cancer: Evaluation of Drug Efficacy (STAMPEDE) investigators. Radiotherapy to the primary tumour for newly diagnosed, metastatic prostate cancer (STAMPEDE): a randomised controlled phase 3 trial. Lancet. 2018 Dec 1;392(10162):2353-2366. doi: 10.1016/S0140-6736(18)32486-3. Epub 2018 Oct 21.",
        "pmid": "30355464"
      },
      {
        "citation": "Clarke NW, Ali A, Ingleby FC, Hoyle A, Amos CL, Attard G, Brawley CD, Calvert J, Chowdhury S, Cook A, Cross W, Dearnaley DP, Douis H, Gilbert D, Gillessen S, Jones RJ, Langley RE, MacNair A, Malik Z, Mason MD, Matheson D, Millman R, Parker CC, Ritchie AWS, Rush H, Russell JM, Brown J, Beesley S, Birtle A, Capaldi L, Gale J, Gibbs S, Lydon A, Nikapota A, Omlin A, O'Sullivan JM, Parikh O, Protheroe A, Rudman S, Srihari NN, Simms M, Tanguay JS, Tolan S, Wagstaff J, Wallace J, Wylie J, Zarkar A, Sydes MR, Parmar MKB, James ND. Addition of docetaxel to hormonal therapy in low- and high-burden metastatic hormone sensitive prostate cancer: long-term survival results from the STAMPEDE trial. Ann Oncol. 2019 Dec 1;30(12):1992-2003. doi: 10.1093/annonc/mdz396.",
        "pmid": "31560068"
      }
    ],
    "hasResults": false,
    "divisions": [
      "research",
      "clinical-medicine"
    ],
    "url": "https://clinicaltrials.gov/study/NCT00268476"
  }
];
